version: '3.7'
services:
  php:
    image: 'php:7.2'
    build: 
      context: .
      dockerfile: php/Dockerfile
    container_name: Apache_php
    volumes: ['www/var/www/site']
    environment: ['php_EXTENTION: pdo/pdo_msqli']
    links: 
      - "db:db"
	
  db:
    image: mariadb:10.4
    build: 
      context: .
      dockerfile: mariadb/Dockerfile
    ports:
      - "8080:30000"
    container_name: Database_mariadb
    volumes:
      - './docker/db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=matisse
      - MYSQL_DATABASE=mariadb

  adminer:
    image: 'adminer'
    build: 
      context: .
      dockerfile: adminer/Dockerfile
    container_name: Adminer
    ports:
      - "8080:50000"
    links: ['apachephp']
    depends_on:
      - db